name: MischiefMaps
version: $version
author: sven@wollinger.email
main: com.mischiefsmp.maps.MischiefMaps
api-version: 1.19
website: wollinger.io
commands:
  imagemap:
    description: "Map Image"
    usage: "/imagemap <url>"
permissions:
  maps.imagemap:
    default: false